id: P006703
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG10281
  title: རྗེ་བཙུན་ཤེས་རབ་སེངྒེའི་རྟོགས་བརྗོད་སྐལ་བཟང་དད་པའི་འདོད་འཇོ་དཔག་བསམ་ཡོངས་འདུའི་ཁྲི་ཤིང་།
  author: ''
  volumes:
    85e4a7e119944d5b8ec6d2c9a9218dbd:
      image_group_id: I1KG10337
      title: ''
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
